name: Deploy to google Cloud App Engine - Develop
'on': 
  workflow_dispatch  
jobs:
 build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Maven build
        run: mvn package
        
      - name: Google App Engine Auth
        uses: google-github-actions/auth@v1.0.0
        with:
          project_id: frisco-business
          credentials_json: ${{secrets.GOOGLE_APP_ENGINE_CREDENTIALS_JSON}}
        
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v1.2.6
        with:
          # version: master
          flags: --no-cache
          deliverables: ${{vars.PATH_TO_JAR}}
